### ISSUE TITLE
Null-Valued expression when running rollback

### ISSUE THREAD

**Issue by declanmc** [openalm/Extension-UtilitiesPack#30]
I get the following error when running the rollback powershell build step containing the sample script from the overview.md: 

![image](https://cloud.githubusercontent.com/assets/10504666/14676828/116c1fe0-0707-11e6-9c66-2b93d9872796.png)

I am running this in VSTS, am I doing something wrong?

**Comment by harshil93** [comment]
The Rollback task is to be used with Release Hub not with Build hub. Its visibility is set to be available only in Release but somehow it showing up in the task list for build hub also.
