### ISSUE TITLE
zip advanced options - overwrite existing zip

### ISSUE THREAD

**Issue by daughey** [openalm/Extension-UtilitiesPack#34]
I would like it if the Zip task had an Advanced options section that contained a checkbox for overwriting an existing zip file.

This would be useful in an incremental build situation where the build agent is re-used without a clean workspace.  It would remove the need to include the Delete Files task in the build.

**Comment by harshil93** [comment]
Working on it.

**Comment by harshil93** [comment]
https://github.com/openalm/Extension-UtilitiesPack/pull/35
