### ISSUE TITLE
Rollback Redeploy status not updating

### ISSUE THREAD

**Issue by schwaizi** [openalm/Extension-UtilitiesPack#37]
Rollback status is not taking the right status on redeploy on specific environment. It always take the task statuses from the first Deploy attempt.
The issue is Rollback task is not using the latest "Redeploy attempt" number from the release.

My idea is to adjust Api Uri to point to Release instead of Task:

`$releasequeryuri = "$($env:SYSTEM_TEAMFOUNDATIONSERVERURI)$($env:SYSTEM_TEAMPROJECT)/_apis/release/releases/$($env:Release_ReleaseId)/environments/$($env:RELEASE_ENVIRONMENTURI.Split('/')[-1])?api-version=2.1-preview.1"`

And select latest attempt number from which to get status on tasks:

```
$tasks = $releasequeryresult.deploySteps | Sort-Object attempt -Descending | select -First 1
$jobtasks = $tasks.tasks | Sort-Object dateStarted
```

**Comment by harshil93** [comment]
@shashban Can we close this ? or something else has to done here ?

**Comment by schwaizi** [comment]
i believe this has been solved
