### ISSUE TITLE
Tokenization task often/always disappears from build definition

### ISSUE THREAD

**Issue by dsoprea** [openalm/Extension-UtilitiesPack#40]
I'll add a task for tokenization to my build definition and the build definition will execute and do everything exactly as expected. However, if I were to reopen the build-definition, the new task will be missing (even though it's actively being used in builds).

If I were to add a task of a different type it will show up as expected on future visits. I've not used this VSIX/task very much, but I've used (read: added-executed-viewed) with this task at least once in the recent past and this did not happen. So, this doesn't necessarily happen every time (or, at least, in the beginning).

Note that I added another tokenization, zip, and unzip task (all provided by this VSIX) to the end of my build-definition, saved it, and opened it back up for edit, and none of the tasks that I had added showed.

I was thinking that this was maybe a bug with how you're classifying the task (visibility/category) or that maybe this is a UUID collision? Let me know if there's anything I can do to help.

**Comment by dsoprea** [comment]
Bump. I'll simply add a tokenization (without a configuration file), save it, reload, and it's gone.

**Comment by pascalberger** [comment]
@dsoprea Do you still see this issue? There was recently [a fix deployed to VSTS](https://twitter.com/DonovanBrown/status/749683634932633604) handling issues with disappearing tasks from extensions.

**Comment by harshil93** [comment]
@dsoprea Doesn't seem to be happening with me. I tried to repro it and many of our production systems are using it without problem. Let me know if it is still happening.  I am closing the issue for now.
