### ISSUE TITLE
Rollback InlineScript fails on TFS 2015 Update 3

### ISSUE THREAD

**Issue by jdshkolnik** [openalm/Extension-UtilitiesPack#49]
I don't know if it'll fail in other environments. Using v0.1.3, I defined an environment variable called Release_Tasks, added the Rollback task, set type to Inline Script, left the default script statement in place (Write-Host..), enabled, always run, and got...

```
System.Management.Automation.RuntimeException:` You cannot call a method on a null-valued expression.
at CallSite.Target(Closure , CallSite , Object , String )
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

**Comment by harshil93** [comment]
@jdshkolnik Can you give a more detailed info of your scenario ? I couldn't make much out of the your last post

**Comment by jdshkolnik** [comment]
![image](https://cloud.githubusercontent.com/assets/2047520/18149946/969fde96-6fb1-11e6-9139-db4a377c78bd.png)

![image](https://cloud.githubusercontent.com/assets/2047520/18150043/27d7662c-6fb2-11e6-9b89-1a87cf80dd13.png)


> 2016-08-31T23:28:03.3426812Z Executing the powershell script: I:\Agent\DEV\tasks\Rollback\1.1.2\Runpowershellwithtaskcontext.ps1
> 2016-08-31T23:28:03.5377007Z ##[debug]Type= InlineScript
> 2016-08-31T23:28:03.5377007Z ##[debug]ScriptPath= I:\Agent\DEV\_work\3\s
> 2016-08-31T23:28:03.5387008Z ##[debug]ScriptArguments= 
> 2016-08-31T23:28:03.5387008Z ##[debug]workingFolder = I:\Agent\DEV\_work\3\s
> 2016-08-31T23:28:03.5397009Z ##[debug]inlineScripe = Write-Host 'Rollback logic goes here as a powershell script'
> 2016-08-31T23:28:03.5577027Z ##[debug]Loading module from path 'I:\Agent\DEV\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Common\Microsoft.TeamFoundation.DistributedTask.Task.Common.dll'.
> 2016-08-31T23:28:03.5897059Z ##[debug]Importing cmdlet 'Complete-Task'.
> 2016-08-31T23:28:03.5897059Z ##[debug]Importing cmdlet 'Get-LocalizedString'.
> 2016-08-31T23:28:03.5897059Z ##[debug]Importing cmdlet 'Set-TaskVariable'.
> 2016-08-31T23:28:03.5907060Z ##[debug]Importing cmdlet 'Set-TaskProgress'.
> 2016-08-31T23:28:03.5907060Z ##[debug]Importing cmdlet 'Add-TaskIssue'.
> 2016-08-31T23:28:03.5917061Z ##[debug]Importing cmdlet 'Write-TaskDetail'.
> 2016-08-31T23:28:03.5917061Z ##[debug]Importing cmdlet 'Find-Files'.
> 2016-08-31T23:28:03.6517121Z ##[error]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
> 2016-08-31T23:28:03.6527122Z ##[error]   at CallSite.Target(Closure , CallSite , Object , String )
> 2016-08-31T23:28:03.6527122Z ##[error]   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
> 2016-08-31T23:28:03.6527122Z ##[error]   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
> 2016-08-31T23:28:03.6537123Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2016-08-31T23:29:03.6637127Z ##[debug]Getting Personal Access Token for the Run
> 2016-08-31T23:29:04.0187482Z ##[debug]Calling http://tfsdev.blah.com:8080/tfs/DefaultCollection/GuineaPig/_apis/release/releases//environments//tasks?api-version=2.1-preview.1 using obtained PAT token
> 2016-08-31T23:29:04.1177581Z ##[debug]GET http://tfsdev.blah.com:8080/tfs/DefaultCollection/GuineaPig/_apis/release/releases//environments//tasks?api-version=2.1-preview.1 with 0-byte payload
> 2016-08-31T23:29:04.8478311Z ##[debug]Could not obtain release tasks status
> 2016-08-31T23:29:04.8718335Z ##[debug]
> 2016-08-31T23:29:04.8718335Z     
> 2016-08-31T23:29:04.8718335Z         Page not found. - Microsoft Team Foundation Server
> 2016-08-31T23:29:04.8728336Z         
> 2016-08-31T23:29:04.8728336Z             body { font-family: Segoe UI, Helvetica Neue, Helvetica, Arial, Verdana; font-size: 16px; height: 100%; }
> 2016-08-31T23:29:04.8738337Z             A { color: #007ACC; text-decoration: none; }
> 2016-08-31T23:29:04.8738337Z             A:hover { text-decoration: underline; }
> 2016-08-31T23:29:04.8738337Z             h1 { font-size: 32px; color: #888; margin-bottom: 0px; }
> 2016-08-31T23:29:04.8748338Z             h2 { font-size: 24px; color: #888; font-weight: normal; margin-top: 0px; }
> 2016-08-31T23:29:04.8748338Z             pre { font-family: Consolas, Courier New, monospace; font-size: 12px; border: 1px solid #ccc; background-color: #eee; padding: 10px;}
> 2016-08-31T23:29:04.8758339Z                 
> 2016-08-31T23:29:04.8758339Z         
> 2016-08-31T23:29:04.8758339Z         
> 2016-08-31T23:29:04.8768340Z             function toggle() {
> 2016-08-31T23:29:04.8768340Z                 var icon = document.getElementById("moreInfoIcon");
> 2016-08-31T23:29:04.8768340Z                 var section = document.getElementById("moreInfo");
> 2016-08-31T23:29:04.8778341Z                 icon.src = section.style.display === ""
> 2016-08-31T23:29:04.8778341Z                     ? "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8%2F9hAAAABGdBTUEAALGPC%2FxhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABl0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjUuODc7gF0AAAB2SURBVDhPY2AYBThDoKWlJa2jo0OO7CBaunTpfxAGGmRCliEgzc%2BePfs%2Ff%2F78%2F01NTZokGwIyAARAhkybNo10Q2AGwAwBeuV%2Fa2urHtEuWb58OWUuABkAC4Pm5mY7om2GKQQZAMJkaQYZAgx5P4rSAclOHjANAOQrXesb81M5AAAAAElFTkSuQmCC"
> 2016-08-31T23:29:04.8778341Z                     : "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8%2F9hAAAABGdBTUEAALGPC%2FxhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABl0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjUuODc7gF0AAABCSURBVDhPY2AYBfQJATU1NWsgLifLNhUVFVeg5v8gTLIBMM2RkZGkG4CsmWQD0DWTbAAowGD%2BRqLJC0SSA24EagAAq9sjtZrUZogAAAAASUVORK5CYII%3D";
> 2016-08-31T23:29:04.8788342Z                 section.style.display = section.style.display === "" ? "none" : "";
> 2016-08-31T23:29:04.8788342Z             }
> 2016-08-31T23:29:04.8798343Z         
> 2016-08-31T23:29:04.8798343Z     
> 2016-08-31T23:29:04.8798343Z     
> 2016-08-31T23:29:04.8808344Z         
> 2016-08-31T23:29:04.8808344Z             
> 2016-08-31T23:29:04.8808344Z                 
> 2016-08-31T23:29:04.8818345Z                 Error
> 2016-08-31T23:29:04.8818345Z                 The page you are looking for is currently unavailable.
> 2016-08-31T23:29:04.8818345Z                 
> 2016-08-31T23:29:04.8828346Z                 Page not found.
> 2016-08-31T23:29:04.8828346Z                  More information about this error
> 2016-08-31T23:29:04.8828346Z                 
> 2016-08-31T23:29:04.8838347Z                     Page not found.
> 2016-08-31T23:29:04.8838347Z                 
> 2016-08-31T23:29:04.8838347Z                 Things you can try:
> 2016-08-31T23:29:04.8848348Z                 
> 2016-08-31T23:29:04.8848348Z                     Refresh the current page
> 2016-08-31T23:29:04.8848348Z                     Go back to the previous page
> 2016-08-31T23:29:04.8858349Z                     
> 2016-08-31T23:29:04.8858349Z                     Sign in as a different user
> 2016-08-31T23:29:04.8858349Z                     
> 2016-08-31T23:29:04.8868350Z                     Submit feedback to Microsoft about this error
> 2016-08-31T23:29:04.8868350Z                 
> 2016-08-31T23:29:04.8868350Z                 
> 2016-08-31T23:29:04.8878351Z                 
> 2016-08-31T23:29:04.8878351Z                     Microsoft Visual Studio Team Foundation Server
> 2016-08-31T23:29:04.8878351Z                     © Microsoft Corporation. All rights reserved.
> 2016-08-31T23:29:04.8888352Z                 
> 2016-08-31T23:29:04.8888352Z             
> 2016-08-31T23:29:04.8898353Z             
> 2016-08-31T23:29:04.8898353Z                 
> 2016-08-31T23:29:04.8898353Z             
> 2016-08-31T23:29:04.8908354Z         
> 2016-08-31T23:29:04.8908354Z     
> 2016-08-31T23:29:04.8908354Z ##[debug]You cannot call a method on a null-valued expression.
> 2016-08-31T23:29:04.8928356Z ##[debug]Release Query unsuccessful.
> 2016-08-31T23:29:04.9488412Z ##[debug]obtained task execution history as {}
> 2016-08-31T23:29:04.9508414Z ##[debug]Running I:\Agent\DEV\_work\3\s
> 2016-08-31T23:29:04.9568420Z ##[debug]Setting working directory to I:\Agent\DEV\_work\3\s
> 2016-08-31T23:29:04.9608424Z ##[debug]Invoking Write-Host 'Rollback logic goes here as a powershell script'
> 2016-08-31T23:29:04.9648428Z Rollback logic goes here as a powershell script
> 2016-08-31T23:29:04.9648428Z ##[debug]Exitting script runpowershellwithtaskcontext

**Comment by harshil93** [comment]
Rollback task is supposed to be used only with Release Management.
