### ISSUE TITLE
Build or release variables are not evaluated

### ISSUE THREAD

**Issue by dzimmyman** [openalm/Extension-UtilitiesPack#51]
...Updating token '__Version__'
 ...Found custom variable 'Version' in build or release definition with value '$(BuildID)'
(Same result with $(Build.BuildID) or $(Release.ReleaseId)

The result is "__Version___" gets replaced with the literal string "$(BuildID)"

**Comment by zsmorris** [comment]
I have also found the same issue.  This should be classified as a bug.

**Comment by harshil93** [comment]
@dzimmyman @zsmorris Can you elaborate a bit more the scenario where this is happening ?

**Comment by harshil93** [comment]
Closing the issue because of no response.
