### ISSUE TITLE
Update documentation with more explanation how to use this

### ISSUE THREAD

**Issue by rajbos** [openalm/Extension-UtilitiesPack#59]
Hi all,

I wanted to used this extension to replace some tokens during build, but I cannot figure out how to do this. The documentation mentions using a Configuration Json file to use for the transformations. If I include this file into TFS, I would include the values to use (perhaps secrets) into TFS. That isn't something I'd recommend :-). Is there a way to use build variables in the config file? 

Adding this to the documentation would help.

**Comment by harshil93** [comment]
You will define the variables in the variable section of Build/ReleaseManagement. 

ConfigurationJson is the alternate option.
