### ISSUE TITLE
use with clickonce

### ISSUE THREAD

**Issue by userjeff3** [openalm/Extension-UtilitiesPack#61]
Has anyone ever successfully used the tokenization step with a clickonce WPF app?

The first problem: The path to the published config file has the app version embedded in it. I can't find a system variable with that value for specifying the "source file name" path. (The config file in the working directory is not used in a clickonce scenario.)

The next problem: If ANY file is modified after a clickonce publish step it will trigger a System.Deployment.Application.InvalidDeploymentException because the hash value won't match the original manifest.

**Comment by harshil93** [comment]
@userjeff3 This seems like a scenario specific issue. The tokenizer task is a generic tool which will transform any type of file given the tokens to replace are of the form __foo__ and the foo variable is declared in Release Variables in VSTS/TFS. 

I will keep the issue open for some time so that others can reply. After that I will close it down.

**Comment by userjeff3** [comment]
I disagree. The first problem I mentioned necessitates the ability to specify target files with a mask. I have since found [another](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens) extension that will do this. This one does not.

If you consider using TFS to release a clickonce application as "scenario specific", then, fine the next problem can be ingnored.

Thanks for replying.

**Comment by harshil93** [comment]
About the first problem. You can specify target files with a mask. For eg. _TargetFilePath = $(System.DefaultWorkingDirectory)/abc.txt_ should work. Am I missing something here ?

I don't know about click once applications, I will have to probably read about it before I can judge whether it could be ignored of not.

**Comment by userjeff3** [comment]
Rather than mask, I should have said wildcard. Something like "$(System.DefaultWorkingDirectory)/drop/*.config".
I agree that the clickonce manifest issue is unrelated.
Thanks again for replying.
