### ISSUE TITLE
Sample *.json file?

### ISSUE THREAD

**Issue by SeamusMcGurk** [openalm/Extension-UtilitiesPack#63]
HI,

   I'm trying to set up a token replacement for my config files.  I have the source filename set to:
$(System.DefaultWorkingDirectory)/TFS Web Build 1.0/Corporate Art\app.RM.config
      (Here, the RM file is the tokenized config file using __token__)
The destination filename is set to the true name of the config file:
Company.Client.Corporate.exe.config
I have the json file on the build server at:
\\0111-03-0555-01\c$\BuildFiles\Transforms.json

The transforms.json file has the following data in it:
[
	{
	"__CompanyTestDomain__": {"QA4"},
	"__Environment__": {"QA4.com"},
	"__CheckForContext__": {"true"},
	"__ServiceTierAppHost__": {"0111-06-0555-00-01.Company.com"},
	"__ServiceTierCsHost__": {"0111-03-0444-00.Company.com"},
	"__ReportServer__": {"0777-02-0111-00-01.Company.com"},
	"__ReportID__": {"systemID"},
	"__ReportDomain__": {"Corp"},
	"__ReportPWord__": {"Password"}
	}
]

The powershell is executed C:\Users\Public\Downloads\agent\tasks\Tokenizer\2.0.2\tokenize.ps1
The next line is grey as opposed to black which all the other information is:
##[debug]Performing the operation "Copy File" on target "Item: 
C:\Agent\_work\85c7a0d97\TFS Web Build 1.0\CorporateArt\app.RM.config 
Destination: C:\Users\Public\Downloads\agent\tasks\Tokenizer\2.0.2\Isagenix.Clients.CorporateBackOffice.exe.config.tmp".
after which, I start getting messages that it's Updating token '__CompanyTestDomain__'
No value found for token '__CompanyTestDomain__'

So, can someone help me figure out what i'm doing wrong?

**Comment by harshil93** [comment]
Take a look here for the right format. https://github.com/openalm/Extension-UtilitiesPack/blob/master/Utilites/overview.md
