### ISSUE TITLE
Missing Output from Rollback Task

### ISSUE THREAD

**Issue by brett3210** [openalm/Extension-UtilitiesPack#65]
I am trying to implement the Rollback Task example shown on https://blogs.msdn.microsoft.com/visualstudioalm/2016/03/28/implement-rollback-with-release-management-for-tfs-2015/

I am unable to locate the "Write-Verbose" and "Copy-Item" execution output when using the "Inline Script" option.  It is not shown in the Release "Logs".  The Log basically only contains the script itself.  Are there any other setup steps required for this Task (e.g. configuration for the Release_Tasks environment variable)?

**Comment by harshil93** [comment]
@shashban Any hints for this ?

**Comment by brett3210** [comment]
I set "System.Debug" to "true" and have some further logging which may help:

2016-12-21T03:11:37.7790785Z ##[debug]Calling https://XXX.vsrm.visualstudio.com/YYY/_apis/release/releases/70/environments/89/tasks?api-version=2.1-preview.1 using obtained PAT token
 
2016-12-21T03:11:37.8070784Z ##[debug]GET https://XXX.vsrm.visualstudio.com/YYY/_apis/release/releases/70/environments/89/tasks?api-version=2.1-preview.1 with 0-byte payload
 
2016-12-21T03:11:39.3278377Z ##[debug]Could not obtain release tasks status
 
2016-12-21T03:11:39.3298366Z ##[debug]The remote server returned an error: (500) Internal Server Error.

**Comment by brett3210** [comment]
Is anyone able to assist with this please?

**Comment by shashban** [comment]
Hi Brett,

Can you confirm the following in this regard?

- Are you using the task on VSTS or TFS On Prem? 
- Does the API https://XXX.vsrm.visualstudio.com/YYY/_apis/release/releases/70/environments/89/tasks?api-version=2.1-preview.1 succeed if you hit it from a browser?
- Can you try https://XXX.vsrm.visualstudio.com/YYY/_apis/release/releases/70/environments/89/tasks also?

To me, it looks like the server you are using no longer supports the specific api version.
Based on your findings, we can determine the right fix

Thanks

**Comment by brett3210** [comment]
Hi Shashban,

Thanks.
- We are using VSTS
- The 1st URL returns
"The XXX.vsrm.visualstudio.com page isn’t working
XXX.vsrm.visualstudio.com is currently unable to handle this request.
HTTP ERROR 500"
- The 2nd URL returns details:
"{"count":8,"value":[{"id":1,"timelineRecordId":" ..."

Regards

**Comment by brett3210** [comment]
Hi Shashban,

Just wondering whether you've had an opportunity to investigate this further?

**Comment by shashban** [comment]
Closing this old issue.
