### ISSUE TITLE
Powershell++ Interpreting StdOut as StdErr

### ISSUE THREAD

**Issue by ijabit** [openalm/Extension-UtilitiesPack#66]
I'm using PowerShell++ to run two NPM install tasks in parallel. I'm using Start-Job with a script block that runs NPM install. The problem is that some of the installed NPM packages have install.js scripts that run which output various status messages into the console. They are informative only but the PowerShell++ task is interpreting them as errors and failing the build!

**Comment by harshil93** [comment]
@ijabit Please use the inline Script option of the Powershell task instead of Powershell++ . Powershell++ will be deprecated.
