### ISSUE TITLE
'Access denied' while trying to use Tokenizer task

### ISSUE THREAD

**Issue by pascalberger** [openalm/Extension-UtilitiesPack#7]
Using the Tokenizer task I get the following error:

```
2016-03-14T09:25:19.6282603Z ##[error]Access to the path 'D:\work\f97caf0d3' is denied.

2016-03-14T09:25:19.6751342Z ##[error]The file D:\work\f97caf0d3.tmp cannot be read: Access to the path 'D:\work\f97caf0d3.tmp' is denied.
```

In the task I have just set the `Source filename` (a WebDeploy SetParameters.xml file). No `Destination filename` and no `Configuration Json filename`, which according to documentation should replace all `__foo__` token with the value of the `foo` variable.

**Comment by anangaur** [comment]
Could you check permissions? I don't seem to see this issue. Will get this investigated anyway.

**Comment by pascalberger** [comment]
What permissions to check? I tried to use this on an On-Prem agent which runs as a Windows service under a specific user. Since the whole agent runs under this account I assume it should have permissions to the work directory of the build, also since he is able to get the source code, build and modify files through other tasks.

The difference is that this task seems to try to write a file directly to the work directory (`D:\work\f97caf0d3.tmp`) instead of to the directory of the build (``D:\work\f97caf0d3\`)

**Comment by harshil93** [comment]
You need to provide the full path to the file and not the folder. For eg. source file name should be of the form "$(System.defaultdirectory)/SetParameters.xml"

**Comment by anangaur** [comment]
This issue should now be fixed.
