### ISSUE TITLE
Testers required for the new version.

### ISSUE THREAD

**Issue by harshil93** [openalm/Extension-UtilitiesPack#84]
Hi @superarchi @Atvaark @RTHilton @scottcrowe @incarnate @pascalberger 

You guys have contributed in the past and I would like you guys to test out the new version
https://github.com/openalm/Extension-UtilitiesPack/blob/master/Utilites/ms-devlabs.utilitytasks-0.1.7.vsix

It mostly contains improvements in Tokenizer with custom variables support ( see the overview.md file )

It would be great if some of you could update your extension manually in VSTS/TFS and let me know if there are any issues. I am running hot with my work at office and will not be able to test it e2e in the next week or so.

**Comment by Atvaark** [comment]
Hey @harshil93,

I've been testing the new version with my TFS 2015 Update 3 since you've created this issue and I haven't noticed and problems yet.

I'm using multiple Tokenizer tasks in my release configuration. One that just uses the environment variables and one that uses this configuration JSON file to replace the logging level of some deployed services. 
```
{
	"default": {
		"ConfigChanges": [{
			"KeyName": "/ns:nlog/ns:rules/ns:logger",
			"Attribute": "minLevel",
			"value": "__logMinLevel__",
			"NamespaceUrl": "http://www.nlog-project.org/schemas/NLog.xsd",
			"NamespacePrefix": "ns"
		}]
	}
}
```

**Comment by harshil93** [comment]
Thanks @Atvaark for the info. I will release the version in marketplace in next week or so.

**Comment by rschoenbach** [comment]
@harshil93 Can you please update the market place with version 0.1.7? I would like to use the default configuration support.

**Comment by harshil93** [comment]
@rschoenbach  Should be in the market place in the next couple of days.

**Comment by rschoenbach** [comment]
@harshil93 Thank you. Just as an FYI, the version for the marketplace was not updated.
![image](https://user-images.githubusercontent.com/9310113/31771328-b3daf976-b4a9-11e7-9615-8628998ac643.png)

**Comment by harshil93** [comment]
@rschoenbach  Thanks for letting me know that. I have updated it to 0.1.8 now.
