### ISSUE TITLE
Shell++ fails with not found echo: null

### ISSUE THREAD

**Issue by sumigoma** [openalm/Extension-UtilitiesPack#87]
The shell++ task (inline script) appears to fail with `not found echo: null`, no matter what I put in the textarea. Am I missing something on the build agent? (using a local VM as my agent).

Edit: The build agent is running Windows 10. I've tracked this down to vso-task-lib being unable to run which() because the build agent is a Windows machine and using cmd by default instead of bash. I have git bash available on the machine. Is it possible to configure the build agent to run everything using bash instead of windows cmd?

**Comment by harshil93** [comment]
Shell task doesn't work on windows. It currently depends on echo and bash linux commands. If both of them are available then it may work on windows but it was never intended to work on windows.
