### ISSUE TITLE
Provide instructions how to build & package this task

### ISSUE THREAD

**Issue by pascalberger** [openalm/Extension-UtilitiesPack#9]
It would be nice to have instructions how to build & package this task for contribute back. Something like done [here in the vso-agent-tasks repo](https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/contribute.md).

**Comment by anangaur** [comment]
Thanks for the feedback. Will. Keeping it open till I put this document in.

**Comment by anangaur** [comment]
I have made changes to README.md to document how to contribute. Hope this helps.

https://github.com/openalm/Extension-UtilitiesPack/blob/master/README.md
