### ISSUE TITLE
Feature Request: Allow PowerShell++ inline script to accept arguments

### ISSUE THREAD

**Issue by deadlydog** [openalm/Extension-UtilitiesPack#95]
It would be nice if the PowerShell++ task allowed arguments to be passed to Inline Scripts like it does with File Path scripts. The default TFS `PowerShell` task allows this, but it's max inline script character length is much too short, which is why I have been using this task instead.

**Comment by harshil93** [comment]
@deadlydog I have deprecated the Powershell++ task as the support cost for it was large. 

I would suggest you to fork out the default Powershell task, change the maxLength field in its JSON and package it in your own extension and publish. You will have a lot of control in that case.

**Comment by deadlydog** [comment]
Well that makes me sad since I already use your awesome extension in many release definitions, but I understand. Thanks for replying back @harshil93 👍
